name: ORY Prettier Format Check
description: A minimal working prettier format check *not* using `npm i`
inputs:
  npmRunArgs:
    description: The args passed to `npm run`
    required: false
    default: format:check
runs:
  using: composite
  steps:
    - name: Install Prettier if it doesn't exist
      run: |-
        if [ ! -f node_modules/.bin/prettier ]; then
          bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/install/prettier.sh)
        fi
      shell: bash
    - name: Check
      run: npm run $INPUT_NPMRUNARGS
      shell: bash
