name: ORY Prettier Format Check
description: A minimal working prettier format check *not* using `npm i`
runs:
  using: composite
  steps:
    - run: |-
        bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/install/prettier.sh)
        npm run format:check
      shell: bash
