name: ORY Prettier Format Check
description: A minimal working prettier format check *not* using `npm i`
inputs:
  npmRunArgs:
    description: The args passed to `npm run`
    required: false
    default: npx prettier --check .
runs:
  using: composite
  steps:
    - name: Prettier
      run: $INPUT_NPMRUNARGS
      shell: bash
